name: RJDG
favicon: null
layout_spectrum: 0.6058479722123593
typography_spectrum: 0.23429712420329452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#372112'
    - '#916a43'
    - '#53b039'
    - '#497f2a'
    - '#3e3e19'
  brandStrength: 0.29724076599814
  lightness: 0.048378087813034654
  saturation: 0.1875
  rhythmicContrast: 0.9536476572975516
purpose: []
